# Execute apps on startup
exec_always --no-startup-id i3-msg 'workspace 1; exec terminator --no-dbus'
exec_always --no-startup-id i3-msg 'workspace 2; exec firefox'
exec_always --no-startup-id i3-msg 'workspace 4; exec terminator --no-dbus --working-dir="~/docs"'
exec_always --no-startup-id i3-msg 'workspace 3; exec obsidian'
